export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST"
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS"
export const GET_NOTES_FAIL = "GET_NOTES_FAIL"

export const GET_GROUPNOTES_REQUEST = "GET_GROUPNOTES_REQUEST";
export const GET_GROUPNOTES_SUCCESS = "GET_GROUPNOTES_SUCCESS";
export const GET_GROUPNOTES_FAIL = "GET_GROUPNOTES_FAIL";



export const CREATE_NOTES_REQUEST = "CREATE_NOTES_REQUEST"
export const CREATE_NOTES_SUCCESS = "CREATE_NOTES_SUCCESS"
export const CREATE_NOTES_FAIL = "CREATE_NOTES_FAIL"


export const UPDATE_NOTES_REQUEST = "UPDATE_NOTES_REQUEST"
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS"
export const UPDATE_NOTES_FAIL = "UPDATE_NOTES_FAIL"


export const DELETE_NOTES_REQUEST = "DELETE_NOTES_REQUEST";
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_FAIL = "DELETE_NOTES_FAIL";










